//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catedraticos
    {
        public double Codigo_Catedratico { get; set; }
        public string Password { get; set; }
        public string Nombre_y_apellidos_del_catedrático { get; set; }
        public string Cedula { get; set; }
        public string Titulo { get; set; }
        public string Titulo2 { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool Esta_Activo { get; set; }
        public Nullable<int> NivelSeguridad { get; set; }
        public string Pais { get; set; }
        public byte[] Huella { get; set; }
        public string Sexo { get; set; }
        public string E_Civil { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public Nullable<int> N_Pais { get; set; }
        public Nullable<int> N_Dep { get; set; }
        public string N_Mun { get; set; }
        public Nullable<double> retencionisr { get; set; }
        public Nullable<double> sueldo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion_Usuario { get; set; }
        public Nullable<int> Rango_Catedraticos { get; set; }
        public string NIT { get; set; }
        public Nullable<double> RegimenFiscal { get; set; }
        public string CuentaReformador { get; set; }
        public string Correo_Institucional { get; set; }
        public Nullable<System.DateTime> Fecha_Vence_Factura { get; set; }
    }
}
