//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaRecibos
    {
        public string Nombre_Completo { get; set; }
        public string Donante { get; set; }
        public string carnet { get; set; }
        public byte semestre_actual { get; set; }
        public string recibo_numero { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_recibo { get; set; }
        public decimal monto { get; set; }
        public byte mes_pago { get; set; }
        public int anio_pago { get; set; }
        public string nombre_concepto { get; set; }
        public int id_concepto { get; set; }
        public string descripcion { get; set; }
        public long id_derivado { get; set; }
        public decimal pago { get; set; }
    }
}
