#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NOTASMESO")]
	public partial class DataAsignaturasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertasignatura(asignatura instance);
    partial void Updateasignatura(asignatura instance);
    partial void Deleteasignatura(asignatura instance);
    partial void InsertCarrera(Carrera instance);
    partial void UpdateCarrera(Carrera instance);
    partial void DeleteCarrera(Carrera instance);
    partial void InsertPensum_Asignaturas(Pensum_Asignaturas instance);
    partial void UpdatePensum_Asignaturas(Pensum_Asignaturas instance);
    partial void DeletePensum_Asignaturas(Pensum_Asignaturas instance);
    #endregion
		
		public DataAsignaturasDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NOTASMESOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataAsignaturasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAsignaturasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAsignaturasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAsignaturasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<asignatura> asignatura
		{
			get
			{
				return this.GetTable<asignatura>();
			}
		}
		
		public System.Data.Linq.Table<Carrera> Carrera
		{
			get
			{
				return this.GetTable<Carrera>();
			}
		}
		
		public System.Data.Linq.Table<Pensum_Asignaturas> Pensum_Asignaturas
		{
			get
			{
				return this.GetTable<Pensum_Asignaturas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.asignatura")]
	public partial class asignatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo_Asignatura;
		
		private string _Asignatura1;
		
		private System.Nullable<int> _Carrera;
		
		private System.Nullable<int> _Semestre;
		
		private System.Nullable<int> _Créditos;
		
		private bool _YaNoseDa;
		
		private System.Nullable<int> _Periodos;
		
		private string _Codigo_Acta;
		
		private string _Complemento;
		
		private System.Nullable<int> _Semestre_Trimestre;
		
		private string _Prerequisito;
		
		private System.Nullable<bool> _Cobrado;
		
		private System.Nullable<int> _Codigo_Certif;
		
		private string _MasDatos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigo_AsignaturaChanging(int value);
    partial void OnCodigo_AsignaturaChanged();
    partial void OnAsignatura1Changing(string value);
    partial void OnAsignatura1Changed();
    partial void OnCarreraChanging(System.Nullable<int> value);
    partial void OnCarreraChanged();
    partial void OnSemestreChanging(System.Nullable<int> value);
    partial void OnSemestreChanged();
    partial void OnCréditosChanging(System.Nullable<int> value);
    partial void OnCréditosChanged();
    partial void OnYaNoseDaChanging(bool value);
    partial void OnYaNoseDaChanged();
    partial void OnPeriodosChanging(System.Nullable<int> value);
    partial void OnPeriodosChanged();
    partial void OnCodigo_ActaChanging(string value);
    partial void OnCodigo_ActaChanged();
    partial void OnComplementoChanging(string value);
    partial void OnComplementoChanged();
    partial void OnSemestre_TrimestreChanging(System.Nullable<int> value);
    partial void OnSemestre_TrimestreChanged();
    partial void OnPrerequisitoChanging(string value);
    partial void OnPrerequisitoChanged();
    partial void OnCobradoChanging(System.Nullable<bool> value);
    partial void OnCobradoChanged();
    partial void OnCodigo_CertifChanging(System.Nullable<int> value);
    partial void OnCodigo_CertifChanged();
    partial void OnMasDatosChanging(string value);
    partial void OnMasDatosChanged();
    #endregion
		
		public asignatura()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Asignatura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Codigo_Asignatura
		{
			get
			{
				return this._Codigo_Asignatura;
			}
			set
			{
				if ((this._Codigo_Asignatura != value))
				{
					this.OnCodigo_AsignaturaChanging(value);
					this.SendPropertyChanging();
					this._Codigo_Asignatura = value;
					this.SendPropertyChanged("Codigo_Asignatura");
					this.OnCodigo_AsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Asignatura", Storage="_Asignatura1", DbType="NVarChar(90)")]
		public string Asignatura1
		{
			get
			{
				return this._Asignatura1;
			}
			set
			{
				if ((this._Asignatura1 != value))
				{
					this.OnAsignatura1Changing(value);
					this.SendPropertyChanging();
					this._Asignatura1 = value;
					this.SendPropertyChanged("Asignatura1");
					this.OnAsignatura1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="Int")]
		public System.Nullable<int> Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this.OnCarreraChanging(value);
					this.SendPropertyChanging();
					this._Carrera = value;
					this.SendPropertyChanged("Carrera");
					this.OnCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre", DbType="Int")]
		public System.Nullable<int> Semestre
		{
			get
			{
				return this._Semestre;
			}
			set
			{
				if ((this._Semestre != value))
				{
					this.OnSemestreChanging(value);
					this.SendPropertyChanging();
					this._Semestre = value;
					this.SendPropertyChanged("Semestre");
					this.OnSemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Créditos", DbType="Int")]
		public System.Nullable<int> Créditos
		{
			get
			{
				return this._Créditos;
			}
			set
			{
				if ((this._Créditos != value))
				{
					this.OnCréditosChanging(value);
					this.SendPropertyChanging();
					this._Créditos = value;
					this.SendPropertyChanged("Créditos");
					this.OnCréditosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YaNoseDa", DbType="Bit NOT NULL")]
		public bool YaNoseDa
		{
			get
			{
				return this._YaNoseDa;
			}
			set
			{
				if ((this._YaNoseDa != value))
				{
					this.OnYaNoseDaChanging(value);
					this.SendPropertyChanging();
					this._YaNoseDa = value;
					this.SendPropertyChanged("YaNoseDa");
					this.OnYaNoseDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodos", DbType="Int")]
		public System.Nullable<int> Periodos
		{
			get
			{
				return this._Periodos;
			}
			set
			{
				if ((this._Periodos != value))
				{
					this.OnPeriodosChanging(value);
					this.SendPropertyChanging();
					this._Periodos = value;
					this.SendPropertyChanged("Periodos");
					this.OnPeriodosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Acta", DbType="NVarChar(50)")]
		public string Codigo_Acta
		{
			get
			{
				return this._Codigo_Acta;
			}
			set
			{
				if ((this._Codigo_Acta != value))
				{
					this.OnCodigo_ActaChanging(value);
					this.SendPropertyChanging();
					this._Codigo_Acta = value;
					this.SendPropertyChanged("Codigo_Acta");
					this.OnCodigo_ActaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complemento", DbType="NVarChar(5)")]
		public string Complemento
		{
			get
			{
				return this._Complemento;
			}
			set
			{
				if ((this._Complemento != value))
				{
					this.OnComplementoChanging(value);
					this.SendPropertyChanging();
					this._Complemento = value;
					this.SendPropertyChanged("Complemento");
					this.OnComplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre_Trimestre", DbType="Int")]
		public System.Nullable<int> Semestre_Trimestre
		{
			get
			{
				return this._Semestre_Trimestre;
			}
			set
			{
				if ((this._Semestre_Trimestre != value))
				{
					this.OnSemestre_TrimestreChanging(value);
					this.SendPropertyChanging();
					this._Semestre_Trimestre = value;
					this.SendPropertyChanged("Semestre_Trimestre");
					this.OnSemestre_TrimestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prerequisito", DbType="NVarChar(90)")]
		public string Prerequisito
		{
			get
			{
				return this._Prerequisito;
			}
			set
			{
				if ((this._Prerequisito != value))
				{
					this.OnPrerequisitoChanging(value);
					this.SendPropertyChanging();
					this._Prerequisito = value;
					this.SendPropertyChanged("Prerequisito");
					this.OnPrerequisitoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cobrado", DbType="Bit")]
		public System.Nullable<bool> Cobrado
		{
			get
			{
				return this._Cobrado;
			}
			set
			{
				if ((this._Cobrado != value))
				{
					this.OnCobradoChanging(value);
					this.SendPropertyChanging();
					this._Cobrado = value;
					this.SendPropertyChanged("Cobrado");
					this.OnCobradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Certif", DbType="Int")]
		public System.Nullable<int> Codigo_Certif
		{
			get
			{
				return this._Codigo_Certif;
			}
			set
			{
				if ((this._Codigo_Certif != value))
				{
					this.OnCodigo_CertifChanging(value);
					this.SendPropertyChanging();
					this._Codigo_Certif = value;
					this.SendPropertyChanged("Codigo_Certif");
					this.OnCodigo_CertifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasDatos", DbType="NVarChar(50)")]
		public string MasDatos
		{
			get
			{
				return this._MasDatos;
			}
			set
			{
				if ((this._MasDatos != value))
				{
					this.OnMasDatosChanging(value);
					this.SendPropertyChanging();
					this._MasDatos = value;
					this.SendPropertyChanged("MasDatos");
					this.OnMasDatosChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carrera")]
	public partial class Carrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Carrera;
		
		private string _Nombre_de_la_carrera;
		
		private System.Nullable<int> _Codigo_Facultad;
		
		private System.Nullable<int> _Semestres;
		
		private string _NomCorto;
		
		private string _Estado;
		
		private string _Pensum_Actual;
		
		private System.Nullable<int> _Conta_Carne;
		
		private string _Departamento;
		
		private System.Nullable<int> _ID_Categoria;
		
		private System.Nullable<int> _Semestre_inicia;
		
		private System.Nullable<int> _Semestre_finaliza;
		
		private string _Plan_E;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CarreraChanging(int value);
    partial void OnId_CarreraChanged();
    partial void OnNombre_de_la_carreraChanging(string value);
    partial void OnNombre_de_la_carreraChanged();
    partial void OnCodigo_FacultadChanging(System.Nullable<int> value);
    partial void OnCodigo_FacultadChanged();
    partial void OnSemestresChanging(System.Nullable<int> value);
    partial void OnSemestresChanged();
    partial void OnNomCortoChanging(string value);
    partial void OnNomCortoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnPensum_ActualChanging(string value);
    partial void OnPensum_ActualChanged();
    partial void OnConta_CarneChanging(System.Nullable<int> value);
    partial void OnConta_CarneChanged();
    partial void OnDepartamentoChanging(string value);
    partial void OnDepartamentoChanged();
    partial void OnID_CategoriaChanging(System.Nullable<int> value);
    partial void OnID_CategoriaChanged();
    partial void OnSemestre_iniciaChanging(System.Nullable<int> value);
    partial void OnSemestre_iniciaChanged();
    partial void OnSemestre_finalizaChanging(System.Nullable<int> value);
    partial void OnSemestre_finalizaChanged();
    partial void OnPlan_EChanging(string value);
    partial void OnPlan_EChanged();
    #endregion
		
		public Carrera()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id Carrera]", Storage="_Id_Carrera", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Carrera
		{
			get
			{
				return this._Id_Carrera;
			}
			set
			{
				if ((this._Id_Carrera != value))
				{
					this.OnId_CarreraChanging(value);
					this.SendPropertyChanging();
					this._Id_Carrera = value;
					this.SendPropertyChanged("Id_Carrera");
					this.OnId_CarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre de la carrera]", Storage="_Nombre_de_la_carrera", DbType="NVarChar(100)")]
		public string Nombre_de_la_carrera
		{
			get
			{
				return this._Nombre_de_la_carrera;
			}
			set
			{
				if ((this._Nombre_de_la_carrera != value))
				{
					this.OnNombre_de_la_carreraChanging(value);
					this.SendPropertyChanging();
					this._Nombre_de_la_carrera = value;
					this.SendPropertyChanged("Nombre_de_la_carrera");
					this.OnNombre_de_la_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Facultad", DbType="Int")]
		public System.Nullable<int> Codigo_Facultad
		{
			get
			{
				return this._Codigo_Facultad;
			}
			set
			{
				if ((this._Codigo_Facultad != value))
				{
					this.OnCodigo_FacultadChanging(value);
					this.SendPropertyChanging();
					this._Codigo_Facultad = value;
					this.SendPropertyChanged("Codigo_Facultad");
					this.OnCodigo_FacultadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestres", DbType="Int")]
		public System.Nullable<int> Semestres
		{
			get
			{
				return this._Semestres;
			}
			set
			{
				if ((this._Semestres != value))
				{
					this.OnSemestresChanging(value);
					this.SendPropertyChanging();
					this._Semestres = value;
					this.SendPropertyChanged("Semestres");
					this.OnSemestresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomCorto", DbType="NVarChar(40)")]
		public string NomCorto
		{
			get
			{
				return this._NomCorto;
			}
			set
			{
				if ((this._NomCorto != value))
				{
					this.OnNomCortoChanging(value);
					this.SendPropertyChanging();
					this._NomCorto = value;
					this.SendPropertyChanged("NomCorto");
					this.OnNomCortoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NChar(10)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pensum_Actual", DbType="NVarChar(50)")]
		public string Pensum_Actual
		{
			get
			{
				return this._Pensum_Actual;
			}
			set
			{
				if ((this._Pensum_Actual != value))
				{
					this.OnPensum_ActualChanging(value);
					this.SendPropertyChanging();
					this._Pensum_Actual = value;
					this.SendPropertyChanged("Pensum_Actual");
					this.OnPensum_ActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conta_Carne", DbType="Int")]
		public System.Nullable<int> Conta_Carne
		{
			get
			{
				return this._Conta_Carne;
			}
			set
			{
				if ((this._Conta_Carne != value))
				{
					this.OnConta_CarneChanging(value);
					this.SendPropertyChanging();
					this._Conta_Carne = value;
					this.SendPropertyChanged("Conta_Carne");
					this.OnConta_CarneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="NVarChar(100)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this.OnDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._Departamento = value;
					this.SendPropertyChanged("Departamento");
					this.OnDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Categoria", DbType="Int")]
		public System.Nullable<int> ID_Categoria
		{
			get
			{
				return this._ID_Categoria;
			}
			set
			{
				if ((this._ID_Categoria != value))
				{
					this.OnID_CategoriaChanging(value);
					this.SendPropertyChanging();
					this._ID_Categoria = value;
					this.SendPropertyChanged("ID_Categoria");
					this.OnID_CategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre_inicia", DbType="Int")]
		public System.Nullable<int> Semestre_inicia
		{
			get
			{
				return this._Semestre_inicia;
			}
			set
			{
				if ((this._Semestre_inicia != value))
				{
					this.OnSemestre_iniciaChanging(value);
					this.SendPropertyChanging();
					this._Semestre_inicia = value;
					this.SendPropertyChanged("Semestre_inicia");
					this.OnSemestre_iniciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre_finaliza", DbType="Int")]
		public System.Nullable<int> Semestre_finaliza
		{
			get
			{
				return this._Semestre_finaliza;
			}
			set
			{
				if ((this._Semestre_finaliza != value))
				{
					this.OnSemestre_finalizaChanging(value);
					this.SendPropertyChanging();
					this._Semestre_finaliza = value;
					this.SendPropertyChanged("Semestre_finaliza");
					this.OnSemestre_finalizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plan_E", DbType="NVarChar(50)")]
		public string Plan_E
		{
			get
			{
				return this._Plan_E;
			}
			set
			{
				if ((this._Plan_E != value))
				{
					this.OnPlan_EChanging(value);
					this.SendPropertyChanging();
					this._Plan_E = value;
					this.SendPropertyChanged("Plan_E");
					this.OnPlan_EChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pensum_Asignaturas")]
	public partial class Pensum_Asignaturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Pensum_Asignatura;
		
		private string _ID_Encabezado_Pensum;
		
		private int _No_curso;
		
		private string _Asignatura;
		
		private int _Creditos;
		
		private System.Nullable<int> _Semestre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Pensum_AsignaturaChanging(int value);
    partial void OnID_Pensum_AsignaturaChanged();
    partial void OnID_Encabezado_PensumChanging(string value);
    partial void OnID_Encabezado_PensumChanged();
    partial void OnNo_cursoChanging(int value);
    partial void OnNo_cursoChanged();
    partial void OnAsignaturaChanging(string value);
    partial void OnAsignaturaChanged();
    partial void OnCreditosChanging(int value);
    partial void OnCreditosChanged();
    partial void OnSemestreChanging(System.Nullable<int> value);
    partial void OnSemestreChanged();
    #endregion
		
		public Pensum_Asignaturas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pensum_Asignatura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Pensum_Asignatura
		{
			get
			{
				return this._ID_Pensum_Asignatura;
			}
			set
			{
				if ((this._ID_Pensum_Asignatura != value))
				{
					this.OnID_Pensum_AsignaturaChanging(value);
					this.SendPropertyChanging();
					this._ID_Pensum_Asignatura = value;
					this.SendPropertyChanged("ID_Pensum_Asignatura");
					this.OnID_Pensum_AsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Encabezado_Pensum", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string ID_Encabezado_Pensum
		{
			get
			{
				return this._ID_Encabezado_Pensum;
			}
			set
			{
				if ((this._ID_Encabezado_Pensum != value))
				{
					this.OnID_Encabezado_PensumChanging(value);
					this.SendPropertyChanging();
					this._ID_Encabezado_Pensum = value;
					this.SendPropertyChanged("ID_Encabezado_Pensum");
					this.OnID_Encabezado_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_curso", DbType="Int NOT NULL")]
		public int No_curso
		{
			get
			{
				return this._No_curso;
			}
			set
			{
				if ((this._No_curso != value))
				{
					this.OnNo_cursoChanging(value);
					this.SendPropertyChanging();
					this._No_curso = value;
					this.SendPropertyChanged("No_curso");
					this.OnNo_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura", DbType="NVarChar(90) NOT NULL", CanBeNull=false)]
		public string Asignatura
		{
			get
			{
				return this._Asignatura;
			}
			set
			{
				if ((this._Asignatura != value))
				{
					this.OnAsignaturaChanging(value);
					this.SendPropertyChanging();
					this._Asignatura = value;
					this.SendPropertyChanged("Asignatura");
					this.OnAsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creditos", DbType="Int NOT NULL")]
		public int Creditos
		{
			get
			{
				return this._Creditos;
			}
			set
			{
				if ((this._Creditos != value))
				{
					this.OnCreditosChanging(value);
					this.SendPropertyChanging();
					this._Creditos = value;
					this.SendPropertyChanged("Creditos");
					this.OnCreditosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre", DbType="Int")]
		public System.Nullable<int> Semestre
		{
			get
			{
				return this._Semestre;
			}
			set
			{
				if ((this._Semestre != value))
				{
					this.OnSemestreChanging(value);
					this.SendPropertyChanging();
					this._Semestre = value;
					this.SendPropertyChanged("Semestre");
					this.OnSemestreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
