#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NOTASMESO")]
	public partial class DataAlumnoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertalumno(alumno instance);
    partial void Updatealumno(alumno instance);
    partial void Deletealumno(alumno instance);
    #endregion
		
		public DataAlumnoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NOTASMESOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataAlumnoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAlumnoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAlumnoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAlumnoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<alumno> alumno
		{
			get
			{
				return this.GetTable<alumno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumno")]
	public partial class alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Número_de_carné;
		
		private string _Password;
		
		private string _Nombre_del_alumno;
		
		private string _Segundo_nombre;
		
		private string _Primer_apellido;
		
		private string _Segundo_apellido;
		
		private string _Apellido_de_casada;
		
		private string _Sexo;
		
		private System.Nullable<System.DateTime> _Fecha_de_Nacimiento;
		
		private string _Lugar_de_Nacimiento;
		
		private string _Nacionalidad;
		
		private string _No_de_Cédula_o_Pasaporte;
		
		private string _Estado_Civil;
		
		private string _Dirección_completa;
		
		private string _Ciudad;
		
		private System.Nullable<int> _Departamento;
		
		private string _Teléfono;
		
		private string _Email;
		
		private string _Nombre_Completo;
		
		private string _Pasaporte;
		
		private string _Jornada;
		
		private string _Usuario;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion_Usuario;
		
		private string _Pensum_Asignado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNúmero_de_carnéChanging(string value);
    partial void OnNúmero_de_carnéChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNombre_del_alumnoChanging(string value);
    partial void OnNombre_del_alumnoChanged();
    partial void OnSegundo_nombreChanging(string value);
    partial void OnSegundo_nombreChanged();
    partial void OnPrimer_apellidoChanging(string value);
    partial void OnPrimer_apellidoChanged();
    partial void OnSegundo_apellidoChanging(string value);
    partial void OnSegundo_apellidoChanged();
    partial void OnApellido_de_casadaChanging(string value);
    partial void OnApellido_de_casadaChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnFecha_de_NacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_de_NacimientoChanged();
    partial void OnLugar_de_NacimientoChanging(string value);
    partial void OnLugar_de_NacimientoChanged();
    partial void OnNacionalidadChanging(string value);
    partial void OnNacionalidadChanged();
    partial void OnNo_de_Cédula_o_PasaporteChanging(string value);
    partial void OnNo_de_Cédula_o_PasaporteChanged();
    partial void OnEstado_CivilChanging(string value);
    partial void OnEstado_CivilChanged();
    partial void OnDirección_completaChanging(string value);
    partial void OnDirección_completaChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnDepartamentoChanging(System.Nullable<int> value);
    partial void OnDepartamentoChanged();
    partial void OnTeléfonoChanging(string value);
    partial void OnTeléfonoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNombre_CompletoChanging(string value);
    partial void OnNombre_CompletoChanged();
    partial void OnPasaporteChanging(string value);
    partial void OnPasaporteChanged();
    partial void OnJornadaChanging(string value);
    partial void OnJornadaChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnFecha_Creacion_UsuarioChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_Creacion_UsuarioChanged();
    partial void OnPensum_AsignadoChanging(string value);
    partial void OnPensum_AsignadoChanged();
    #endregion
		
		public alumno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Número de carné]", Storage="_Número_de_carné", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Número_de_carné
		{
			get
			{
				return this._Número_de_carné;
			}
			set
			{
				if ((this._Número_de_carné != value))
				{
					this.OnNúmero_de_carnéChanging(value);
					this.SendPropertyChanging();
					this._Número_de_carné = value;
					this.SendPropertyChanged("Número_de_carné");
					this.OnNúmero_de_carnéChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre del alumno]", Storage="_Nombre_del_alumno", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre_del_alumno
		{
			get
			{
				return this._Nombre_del_alumno;
			}
			set
			{
				if ((this._Nombre_del_alumno != value))
				{
					this.OnNombre_del_alumnoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_del_alumno = value;
					this.SendPropertyChanged("Nombre_del_alumno");
					this.OnNombre_del_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Segundo nombre]", Storage="_Segundo_nombre", DbType="NVarChar(50)")]
		public string Segundo_nombre
		{
			get
			{
				return this._Segundo_nombre;
			}
			set
			{
				if ((this._Segundo_nombre != value))
				{
					this.OnSegundo_nombreChanging(value);
					this.SendPropertyChanging();
					this._Segundo_nombre = value;
					this.SendPropertyChanged("Segundo_nombre");
					this.OnSegundo_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primer apellido]", Storage="_Primer_apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Primer_apellido
		{
			get
			{
				return this._Primer_apellido;
			}
			set
			{
				if ((this._Primer_apellido != value))
				{
					this.OnPrimer_apellidoChanging(value);
					this.SendPropertyChanging();
					this._Primer_apellido = value;
					this.SendPropertyChanged("Primer_apellido");
					this.OnPrimer_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Segundo apellido]", Storage="_Segundo_apellido", DbType="NVarChar(50)")]
		public string Segundo_apellido
		{
			get
			{
				return this._Segundo_apellido;
			}
			set
			{
				if ((this._Segundo_apellido != value))
				{
					this.OnSegundo_apellidoChanging(value);
					this.SendPropertyChanging();
					this._Segundo_apellido = value;
					this.SendPropertyChanged("Segundo_apellido");
					this.OnSegundo_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Apellido de casada]", Storage="_Apellido_de_casada", DbType="NVarChar(50)")]
		public string Apellido_de_casada
		{
			get
			{
				return this._Apellido_de_casada;
			}
			set
			{
				if ((this._Apellido_de_casada != value))
				{
					this.OnApellido_de_casadaChanging(value);
					this.SendPropertyChanging();
					this._Apellido_de_casada = value;
					this.SendPropertyChanged("Apellido_de_casada");
					this.OnApellido_de_casadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="NVarChar(50)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Nacimiento]", Storage="_Fecha_de_Nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_de_Nacimiento
		{
			get
			{
				return this._Fecha_de_Nacimiento;
			}
			set
			{
				if ((this._Fecha_de_Nacimiento != value))
				{
					this.OnFecha_de_NacimientoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_de_Nacimiento = value;
					this.SendPropertyChanged("Fecha_de_Nacimiento");
					this.OnFecha_de_NacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lugar de Nacimiento]", Storage="_Lugar_de_Nacimiento", DbType="NVarChar(100)")]
		public string Lugar_de_Nacimiento
		{
			get
			{
				return this._Lugar_de_Nacimiento;
			}
			set
			{
				if ((this._Lugar_de_Nacimiento != value))
				{
					this.OnLugar_de_NacimientoChanging(value);
					this.SendPropertyChanging();
					this._Lugar_de_Nacimiento = value;
					this.SendPropertyChanged("Lugar_de_Nacimiento");
					this.OnLugar_de_NacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacionalidad", DbType="NVarChar(50)")]
		public string Nacionalidad
		{
			get
			{
				return this._Nacionalidad;
			}
			set
			{
				if ((this._Nacionalidad != value))
				{
					this.OnNacionalidadChanging(value);
					this.SendPropertyChanging();
					this._Nacionalidad = value;
					this.SendPropertyChanged("Nacionalidad");
					this.OnNacionalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[No de Cédula o Pasaporte]", Storage="_No_de_Cédula_o_Pasaporte", DbType="NVarChar(50)")]
		public string No_de_Cédula_o_Pasaporte
		{
			get
			{
				return this._No_de_Cédula_o_Pasaporte;
			}
			set
			{
				if ((this._No_de_Cédula_o_Pasaporte != value))
				{
					this.OnNo_de_Cédula_o_PasaporteChanging(value);
					this.SendPropertyChanging();
					this._No_de_Cédula_o_Pasaporte = value;
					this.SendPropertyChanged("No_de_Cédula_o_Pasaporte");
					this.OnNo_de_Cédula_o_PasaporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estado Civil]", Storage="_Estado_Civil", DbType="NVarChar(50)")]
		public string Estado_Civil
		{
			get
			{
				return this._Estado_Civil;
			}
			set
			{
				if ((this._Estado_Civil != value))
				{
					this.OnEstado_CivilChanging(value);
					this.SendPropertyChanging();
					this._Estado_Civil = value;
					this.SendPropertyChanged("Estado_Civil");
					this.OnEstado_CivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dirección completa]", Storage="_Dirección_completa", DbType="NVarChar(150)")]
		public string Dirección_completa
		{
			get
			{
				return this._Dirección_completa;
			}
			set
			{
				if ((this._Dirección_completa != value))
				{
					this.OnDirección_completaChanging(value);
					this.SendPropertyChanging();
					this._Dirección_completa = value;
					this.SendPropertyChanged("Dirección_completa");
					this.OnDirección_completaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="NVarChar(50)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="Int")]
		public System.Nullable<int> Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this.OnDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._Departamento = value;
					this.SendPropertyChanged("Departamento");
					this.OnDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teléfono", DbType="NVarChar(50)")]
		public string Teléfono
		{
			get
			{
				return this._Teléfono;
			}
			set
			{
				if ((this._Teléfono != value))
				{
					this.OnTeléfonoChanging(value);
					this.SendPropertyChanging();
					this._Teléfono = value;
					this.SendPropertyChanged("Teléfono");
					this.OnTeléfonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Completo", DbType="NVarChar(50)")]
		public string Nombre_Completo
		{
			get
			{
				return this._Nombre_Completo;
			}
			set
			{
				if ((this._Nombre_Completo != value))
				{
					this.OnNombre_CompletoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Completo = value;
					this.SendPropertyChanged("Nombre_Completo");
					this.OnNombre_CompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasaporte", DbType="NVarChar(50)")]
		public string Pasaporte
		{
			get
			{
				return this._Pasaporte;
			}
			set
			{
				if ((this._Pasaporte != value))
				{
					this.OnPasaporteChanging(value);
					this.SendPropertyChanging();
					this._Pasaporte = value;
					this.SendPropertyChanged("Pasaporte");
					this.OnPasaporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jornada", DbType="NVarChar(15)")]
		public string Jornada
		{
			get
			{
				return this._Jornada;
			}
			set
			{
				if ((this._Jornada != value))
				{
					this.OnJornadaChanging(value);
					this.SendPropertyChanging();
					this._Jornada = value;
					this.SendPropertyChanged("Jornada");
					this.OnJornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion_Usuario", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion_Usuario
		{
			get
			{
				return this._Fecha_Creacion_Usuario;
			}
			set
			{
				if ((this._Fecha_Creacion_Usuario != value))
				{
					this.OnFecha_Creacion_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Creacion_Usuario = value;
					this.SendPropertyChanged("Fecha_Creacion_Usuario");
					this.OnFecha_Creacion_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pensum_Asignado", DbType="NVarChar(20)")]
		public string Pensum_Asignado
		{
			get
			{
				return this._Pensum_Asignado;
			}
			set
			{
				if ((this._Pensum_Asignado != value))
				{
					this.OnPensum_AsignadoChanging(value);
					this.SendPropertyChanging();
					this._Pensum_Asignado = value;
					this.SendPropertyChanged("Pensum_Asignado");
					this.OnPensum_AsignadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
