//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escaneos
    {
        public int IdEscaneo { get; set; }
        public int IdAdmin { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string Carne { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string nombrearchivo { get; set; }
        public string idArchivo { get; set; }
        public string idDirectorio { get; set; }
    }
}
