#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NOTASMESO")]
	public partial class Historial_NotasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public Historial_NotasDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NOTASMESOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Historial_NotasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Historial_NotasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Historial_NotasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Historial_NotasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vista_Notas> Vista_Notas
		{
			get
			{
				return this.GetTable<Vista_Notas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_Notas")]
	public partial class Vista_Notas
	{
		
		private string _Asignatura;
		
		private System.Nullable<int> _Zona;
		
		private System.Nullable<int> _Examen_final;
		
		private System.Nullable<int> _Nota_final;
		
		private string _Nombre_y_apellidos_del_catedrático;
		
		private System.Nullable<int> _semestre_Cursado;
		
		private string _Número_de_carné;
		
		private string _Seccion;
		
		private System.Nullable<int> _semestre;
		
		private string _Apellidos;
		
		private string _Codigo_Asignacion_Curso_Profesor;
		
		private string _Codigo_Acta;
		
		private System.Nullable<System.DateTime> _Fecha_aprobación;
		
		private System.Nullable<int> _ano;
		
		private bool _gano;
		
		private bool _No_Obligatorio;
		
		private string _Nombre_Completo;
		
		private string _TipoNota;
		
		private string _Nombre_de_la_carrera;
		
		private string _facultad;
		
		private System.Nullable<int> _Créditos;
		
		private int _Codigo_Asignatura;
		
		private string _Departamento;
		
		private string _NomCorto;
		
		private System.Nullable<bool> _Visible;
		
		private System.Nullable<bool> _Derecho_Examen;
		
		private string _Finales;
		
		private string _Numero_Acta;
		
		private int _Id_Carrera;
		
		public Vista_Notas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura", DbType="NVarChar(141)")]
		public string Asignatura
		{
			get
			{
				return this._Asignatura;
			}
			set
			{
				if ((this._Asignatura != value))
				{
					this._Asignatura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zona", DbType="Int")]
		public System.Nullable<int> Zona
		{
			get
			{
				return this._Zona;
			}
			set
			{
				if ((this._Zona != value))
				{
					this._Zona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Examen final]", Storage="_Examen_final", DbType="Int")]
		public System.Nullable<int> Examen_final
		{
			get
			{
				return this._Examen_final;
			}
			set
			{
				if ((this._Examen_final != value))
				{
					this._Examen_final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nota final]", Storage="_Nota_final", DbType="Int")]
		public System.Nullable<int> Nota_final
		{
			get
			{
				return this._Nota_final;
			}
			set
			{
				if ((this._Nota_final != value))
				{
					this._Nota_final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre y apellidos del catedrático]", Storage="_Nombre_y_apellidos_del_catedrático", DbType="NVarChar(255)")]
		public string Nombre_y_apellidos_del_catedrático
		{
			get
			{
				return this._Nombre_y_apellidos_del_catedrático;
			}
			set
			{
				if ((this._Nombre_y_apellidos_del_catedrático != value))
				{
					this._Nombre_y_apellidos_del_catedrático = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semestre_Cursado", DbType="Int")]
		public System.Nullable<int> semestre_Cursado
		{
			get
			{
				return this._semestre_Cursado;
			}
			set
			{
				if ((this._semestre_Cursado != value))
				{
					this._semestre_Cursado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Número de carné]", Storage="_Número_de_carné", DbType="NVarChar(50)")]
		public string Número_de_carné
		{
			get
			{
				return this._Número_de_carné;
			}
			set
			{
				if ((this._Número_de_carné != value))
				{
					this._Número_de_carné = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seccion", DbType="NVarChar(50)")]
		public string Seccion
		{
			get
			{
				return this._Seccion;
			}
			set
			{
				if ((this._Seccion != value))
				{
					this._Seccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semestre", DbType="Int")]
		public System.Nullable<int> semestre
		{
			get
			{
				return this._semestre;
			}
			set
			{
				if ((this._semestre != value))
				{
					this._semestre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="NVarChar(100)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Asignacion_Curso_Profesor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Codigo_Asignacion_Curso_Profesor
		{
			get
			{
				return this._Codigo_Asignacion_Curso_Profesor;
			}
			set
			{
				if ((this._Codigo_Asignacion_Curso_Profesor != value))
				{
					this._Codigo_Asignacion_Curso_Profesor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Acta", DbType="NVarChar(50)")]
		public string Codigo_Acta
		{
			get
			{
				return this._Codigo_Acta;
			}
			set
			{
				if ((this._Codigo_Acta != value))
				{
					this._Codigo_Acta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha aprobación]", Storage="_Fecha_aprobación", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_aprobación
		{
			get
			{
				return this._Fecha_aprobación;
			}
			set
			{
				if ((this._Fecha_aprobación != value))
				{
					this._Fecha_aprobación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="Int")]
		public System.Nullable<int> ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					this._ano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gano", DbType="Bit NOT NULL")]
		public bool gano
		{
			get
			{
				return this._gano;
			}
			set
			{
				if ((this._gano != value))
				{
					this._gano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Obligatorio", DbType="Bit NOT NULL")]
		public bool No_Obligatorio
		{
			get
			{
				return this._No_Obligatorio;
			}
			set
			{
				if ((this._No_Obligatorio != value))
				{
					this._No_Obligatorio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Completo", DbType="NVarChar(50)")]
		public string Nombre_Completo
		{
			get
			{
				return this._Nombre_Completo;
			}
			set
			{
				if ((this._Nombre_Completo != value))
				{
					this._Nombre_Completo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoNota", DbType="NVarChar(50)")]
		public string TipoNota
		{
			get
			{
				return this._TipoNota;
			}
			set
			{
				if ((this._TipoNota != value))
				{
					this._TipoNota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre de la carrera]", Storage="_Nombre_de_la_carrera", DbType="NVarChar(100)")]
		public string Nombre_de_la_carrera
		{
			get
			{
				return this._Nombre_de_la_carrera;
			}
			set
			{
				if ((this._Nombre_de_la_carrera != value))
				{
					this._Nombre_de_la_carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facultad", DbType="NVarChar(100)")]
		public string facultad
		{
			get
			{
				return this._facultad;
			}
			set
			{
				if ((this._facultad != value))
				{
					this._facultad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Créditos", DbType="Int")]
		public System.Nullable<int> Créditos
		{
			get
			{
				return this._Créditos;
			}
			set
			{
				if ((this._Créditos != value))
				{
					this._Créditos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Asignatura", DbType="Int NOT NULL")]
		public int Codigo_Asignatura
		{
			get
			{
				return this._Codigo_Asignatura;
			}
			set
			{
				if ((this._Codigo_Asignatura != value))
				{
					this._Codigo_Asignatura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="NVarChar(100)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomCorto", DbType="NVarChar(40)")]
		public string NomCorto
		{
			get
			{
				return this._NomCorto;
			}
			set
			{
				if ((this._NomCorto != value))
				{
					this._NomCorto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit")]
		public System.Nullable<bool> Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this._Visible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Derecho_Examen", DbType="Bit")]
		public System.Nullable<bool> Derecho_Examen
		{
			get
			{
				return this._Derecho_Examen;
			}
			set
			{
				if ((this._Derecho_Examen != value))
				{
					this._Derecho_Examen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finales", DbType="NVarChar(50)")]
		public string Finales
		{
			get
			{
				return this._Finales;
			}
			set
			{
				if ((this._Finales != value))
				{
					this._Finales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Acta", DbType="NVarChar(50)")]
		public string Numero_Acta
		{
			get
			{
				return this._Numero_Acta;
			}
			set
			{
				if ((this._Numero_Acta != value))
				{
					this._Numero_Acta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id Carrera]", Storage="_Id_Carrera", DbType="Int NOT NULL")]
		public int Id_Carrera
		{
			get
			{
				return this._Id_Carrera;
			}
			set
			{
				if ((this._Id_Carrera != value))
				{
					this._Id_Carrera = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
