//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NOTASMESOEntitiesEscaneosGuate : DbContext
    {
        public NOTASMESOEntitiesEscaneosGuate()
            : base(GetConnectionString())
        {
        }

        private static string GetConnectionString()

        {

            // Llamar al método CadenaConexionLinq 

            var connStr = UtilidadesDB.CadenaConexionLinq("SQL_CONN_NOTASMESOGUATE", "Model.ModelEscaneosGuate");

            return connStr;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Escaneos> Escaneos { get; set; }
        public virtual DbSet<View_EscaneosGeneral> View_EscaneosGeneral { get; set; }
        public virtual DbSet<View_EscaneosDetalle> View_EscaneosDetalle { get; set; }
    }
}
