#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NOTASMESO")]
	public partial class ProcedimientosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ProcedimientosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NOTASMESOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProcedimientosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProcedimientosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProcedimientosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProcedimientosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Ver_Cursos_Alumno")]
		public ISingleResult<Ver_Cursos_AlumnoResult> Ver_Cursos_Alumno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string carnet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carnet, opcion);
			return ((ISingleResult<Ver_Cursos_AlumnoResult>)(result.ReturnValue));
		}
	}
	
	public partial class Ver_Cursos_AlumnoResult
	{
		
		private string _Asignatura;
		
		private System.Nullable<int> _Punteo;
		
		private System.Nullable<int> _Semestre;
		
		public Ver_Cursos_AlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura", DbType="NVarChar(90)")]
		public string Asignatura
		{
			get
			{
				return this._Asignatura;
			}
			set
			{
				if ((this._Asignatura != value))
				{
					this._Asignatura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Punteo", DbType="Int")]
		public System.Nullable<int> Punteo
		{
			get
			{
				return this._Punteo;
			}
			set
			{
				if ((this._Punteo != value))
				{
					this._Punteo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre", DbType="Int")]
		public System.Nullable<int> Semestre
		{
			get
			{
				return this._Semestre;
			}
			set
			{
				if ((this._Semestre != value))
				{
					this._Semestre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
