//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatedraticosSalud
    {
        public int IdSalud { get; set; }
        public Nullable<double> IdCatedratico { get; set; }
        public string TelefonoEmergencia { get; set; }
        public string ContactoEmergencia { get; set; }
        public string RelacionContacto { get; set; }
        public string Medico { get; set; }
        public string TelefonoMedico { get; set; }
        public Nullable<int> Id_Grupo { get; set; }
        public string NoSeguroMedico { get; set; }
        public string EmpresaSeguroMedico { get; set; }
        public string AlergicoMedicamentos { get; set; }
    
        public virtual Catedraticos Catedraticos { get; set; }
    }
}
