//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catedraticos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catedraticos()
        {
            this.CatedraticosColegios = new HashSet<CatedraticosColegios>();
            this.CatedraticosDocumentos = new HashSet<CatedraticosDocumentos>();
            this.CatedraticosEmpresas = new HashSet<CatedraticosEmpresas>();
            this.CatedraticosIdiomas = new HashSet<CatedraticosIdiomas>();
            this.CatedraticosSalud = new HashSet<CatedraticosSalud>();
            this.CatedraticosSaludEnfermedades = new HashSet<CatedraticosSaludEnfermedades>();
            this.CatedraticosTitulos = new HashSet<CatedraticosTitulos>();
        }
    
        public double Codigo_Catedratico { get; set; }
        public string Password { get; set; }
        public string Nombre_y_apellidos_del_catedrático { get; set; }
        public string Cedula { get; set; }
        public string Titulo { get; set; }
        public string Titulo2 { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool Esta_Activo { get; set; }
        public Nullable<int> NivelSeguridad { get; set; }
        public string Pais { get; set; }
        public byte[] Huella { get; set; }
        public string Sexo { get; set; }
        public string E_Civil { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public Nullable<int> N_Pais { get; set; }
        public Nullable<int> N_Dep { get; set; }
        public string N_Mun { get; set; }
        public Nullable<double> retencionisr { get; set; }
        public Nullable<double> sueldo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion_Usuario { get; set; }
        public Nullable<int> Rango_Catedraticos { get; set; }
        public string NIT { get; set; }
        public Nullable<double> RegimenFiscal { get; set; }
        public string CuentaReformador { get; set; }
        public string Correo_Institucional { get; set; }
        public Nullable<System.DateTime> Fecha_Vence_Factura { get; set; }
        public string Titulo_Superior { get; set; }
        public string Oficina { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Residencia { get; set; }
        public string CuentaIndustrial { get; set; }
        public Nullable<int> IdTipoDocente { get; set; }
    
        public virtual Catedraticos_Rangos Catedraticos_Rangos { get; set; }
        public virtual CatedraticosTipo CatedraticosTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatedraticosColegios> CatedraticosColegios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatedraticosDocumentos> CatedraticosDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatedraticosEmpresas> CatedraticosEmpresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatedraticosIdiomas> CatedraticosIdiomas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatedraticosSalud> CatedraticosSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatedraticosSaludEnfermedades> CatedraticosSaludEnfermedades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatedraticosTitulos> CatedraticosTitulos { get; set; }
    }
}
