//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatedraticosColegios
    {
        public int IdAsignacionColegio { get; set; }
        public double IdCatedratico { get; set; }
        public int IdColegio { get; set; }
        public string NoColegiado { get; set; }
        public System.DateTime VencimientoColegiado { get; set; }
    
        public virtual Catedraticos Catedraticos { get; set; }
        public virtual ColegiosProfesionales ColegiosProfesionales { get; set; }
    }
}
