//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatedraticosEmpresas
    {
        public int idEmpresaCatedatico { get; set; }
        public Nullable<double> IdCatedratico { get; set; }
        public string IGSS { get; set; }
        public string Empresa { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string email { get; set; }
    
        public virtual Catedraticos Catedraticos { get; set; }
    }
}
