//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatedraticosIdiomas
    {
        public int IdDocenteIdioma { get; set; }
        public double IdCatedratico { get; set; }
        public int idIdioma { get; set; }
    
        public virtual Catedraticos Catedraticos { get; set; }
    }
}
