//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatedraticosDocumentos
    {
        public int id { get; set; }
        public double idCatedratico { get; set; }
        public string idDocumento { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<System.DateTime> FechaSubida { get; set; }
    
        public virtual Catedraticos Catedraticos { get; set; }
    }
}
