//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visor_de_Documentos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NOTASMESOEntitiesCatedraticoXela : DbContext
    {
        public NOTASMESOEntitiesCatedraticoXela()
            : base("name=NOTASMESOEntitiesCatedraticoXela")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catedraticos> Catedraticos { get; set; }
        public virtual DbSet<Catedraticos_Rangos> Catedraticos_Rangos { get; set; }
        public virtual DbSet<CatedraticosColegios> CatedraticosColegios { get; set; }
        public virtual DbSet<CatedraticosDocumentos> CatedraticosDocumentos { get; set; }
        public virtual DbSet<CatedraticosEmpresas> CatedraticosEmpresas { get; set; }
        public virtual DbSet<CatedraticosIdiomas> CatedraticosIdiomas { get; set; }
        public virtual DbSet<CatedraticosSalud> CatedraticosSalud { get; set; }
        public virtual DbSet<CatedraticosSaludEnfermedades> CatedraticosSaludEnfermedades { get; set; }
        public virtual DbSet<CatedraticosTipo> CatedraticosTipo { get; set; }
        public virtual DbSet<CatedraticosTitulos> CatedraticosTitulos { get; set; }
        public virtual DbSet<ColegiosProfesionales> ColegiosProfesionales { get; set; }
    }
}
